### ISSUE TITLE
GUI is not opening 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [DataWithDanny/odsc-sql-masterclass#4]
Hi @DataWithDanny 

I have run `docker -compose up` and it builds successfully. When I open localhost : 3000 , it's not working

here are some ref screenshots :-

![image](https://user-images.githubusercontent.com/42869040/134176416-480d5dd4-d3e4-46b6-b62b-473ba563634c.png)
![image](https://user-images.githubusercontent.com/42869040/134176575-0961fa8f-85e0-4066-9439-bb301024d86a.png)

![image](https://user-images.githubusercontent.com/42869040/134176470-0f609192-7d01-4d12-9f57-45e59b5016df.png)

![image](https://user-images.githubusercontent.com/42869040/134176285-913aebc5-c6c6-4361-90d6-667c46ba8766.png)

How to fix this issue?
Thanks

**Comment by DataWithDanny** [comment]
Mmmm that's weird! Everything seems to be working fine...

Can you try hitting http://localhost:3000 instead - sometimes the https:// will get appended by default maybe?

**Comment by VinayChaudhari1996** [comment]
> Mmmm that's weird! Everything seems to be working fine...
> 
> Can you try hitting http://localhost:3000 instead - sometimes the https:// will get appended by default maybe?

Same issue :/

**Comment by DataWithDanny** [comment]
Honestly I'm not quite sure what is going wrong :/

You might have a different Docker daemon running also - you can try switching it to see if it makes any difference?

Worst case - try restarting the entire Docker service/app and restart your computer too...

I have PTSD with Windows and Docker lol - the first thing I get my Serious SQL students to do in the course is to install Docker - it's SUCH a pain on Windows, and it's an even bigger pain to write tutorials on how to do it! 🥲

**Comment by DataWithDanny** [comment]
Other issues could be firewall/network and ports related, maybe VPN settings too - perhaps the TLS option in your Docker settings?

A lot of things can go wrong :(
