### ISSUE TITLE
Sql course

### ISSUE THREAD

**Issue by usamaozzo** [DataWithDanny/odsc-sql-masterclass#9]

**Comment by gojvb** [comment]
The 'SQL Course' hyperlink contains an error in the URL. There's a backslash before '.com'.

Attached screenshot showing the URL when hovering over the hyperlink.

![image](https://user-images.githubusercontent.com/26420425/142269955-5427d1e5-16d3-48bc-9961-be79c890d12a.png)

**Comment by DataWithDanny** [comment]
Thank you for spotting this - I'm sorry it took so long for me to make this change on such an important link!

Fixed in #19
